### ISSUE TITLE
I have instaled spatialDE, but it run with error "Error in system2(python.cmd, c("-E", "-c", shQuote("print(1)")), stdout = TRUE,  :    error in running command"

### ISSUE THREAD

**Issue by forrwill** [sales-lab/spatialDE#23]
> py_available
py_available
> py_available()
[1] TRUE
> spatialDE_res <- spatialDE(counts, coordinates = x,verbose = FALSE)
Error in system2(python.cmd, c("-E", "-c", shQuote("print(1)")), stdout = TRUE,  : 
  error in running command
> python.cmd
Error: object 'python.cmd' not found

**Comment by davidecrs** [comment]
Hi @forrwill,

can you please give me more details about your error? 
For example, did you install the package through Bioconductor or Github? 
Can you print your `sessionInfo()`?

Best regards

**Comment by gbrsales** [comment]
No information available to reproduce.
